// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gym_tracker_report/core/storage/hive/models/app_settings_hive_model.dart';
import 'package:gym_tracker_report/core/storage/hive/models/migration_meta_hive_model.dart';
import 'package:gym_tracker_report/features/daily_report/data/models/daily_report_hive_model.dart';
import 'package:gym_tracker_report/features/workout/data/models/exercise_log_hive_model.dart';
import 'package:gym_tracker_report/features/workout/data/models/exercise_set_log_hive_model.dart';
import 'package:gym_tracker_report/features/workout/data/models/workout_session_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(DailyReportHiveModelAdapter());
    registerAdapter(ExerciseLogHiveModelAdapter());
    registerAdapter(ExerciseSetLogHiveModelAdapter());
    registerAdapter(MigrationMetaHiveModelAdapter());
    registerAdapter(WorkoutSessionHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(DailyReportHiveModelAdapter());
    registerAdapter(ExerciseLogHiveModelAdapter());
    registerAdapter(ExerciseSetLogHiveModelAdapter());
    registerAdapter(MigrationMetaHiveModelAdapter());
    registerAdapter(WorkoutSessionHiveModelAdapter());
  }
}
