import 'package:flutter/material.dart';
import '../theme/report_theme_tokens.dart';

class ReportFooter extends StatelessWidget {
  final TextDirection direction;
  final String text;

  const ReportFooter({
    super.key,
    this.direction = TextDirection.ltr,
    this.text = 'GENERATED BY GYM TRACKER',
  });

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: direction,
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 16),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ShaderMask(
              shaderCallback: (bounds) =>
                  ReportThemeTokens.primaryGradient.createShader(bounds),
              child: const Icon(
                Icons.bolt_rounded,
                size: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(width: 8),
            Text(
              text,
              style: direction == TextDirection.rtl
                  ? ReportThemeTokens.arabicBody(
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                      color: ReportThemeTokens.textMuted,
                    )
                  : ReportThemeTokens.outfitSubtext(
                      fontSize: 11,
                      fontWeight: FontWeight.w800,
                      color: ReportThemeTokens.textMuted,
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
